name = "hay-school-frontend"
compatibility_date = "2024-01-01"
account_id = "2162d7153d40325f96db8ef869fee06b"

[env.production]
# Pages configuration
pages_build_output_dir = "dist"

# Environment variables for production
[vars]
NODE_ENV = "production"
VITE_API_URL = "https://hay-school-backend.hayschool.workers.dev"

# Build configuration
[build]
command = "npm run build"
cwd = "hay-school-react"

# Pages deployment configuration
[[pages_build_config]]
# Build command for Pages
build_command = "npm run build"
# Build output directory
destination_dir = "dist"
# Root directory for the build
root_dir = "hay-school-react"
# Source files for Pages functions (optional)
# functions_dir = "functions"
