name = "hay-school-frontend"
compatibility_date = "2024-01-01"

# Pages configuration - must be at root level for Pages projects
pages_build_output_dir = "dist"

# Environment variables for production
[vars]
NODE_ENV = "production"
VITE_API_URL = "https://hay-school-backend.hayschool.workers.dev"
