name: Deploy to Cloudflare

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Test job - runs on all pushes and PRs
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Frontend tests
      - name: Setup Node.js ${{ matrix.node-version }} (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: hay-school-react/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd hay-school-react
          npm ci

      - name: Type check frontend
        run: |
          cd hay-school-react
          npm run type-check

      - name: Lint frontend
        run: |
          cd hay-school-react
          npm run lint

      - name: Build frontend
        run: |
          cd hay-school-react
          npm run build

      # Backend tests
      - name: Setup Node.js ${{ matrix.node-version }} (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend-hono/package-lock.json

      - name: Install backend dependencies
        run: |
          cd backend-hono
          npm ci

      - name: Type check backend
        run: |
          cd backend-hono
          npm run type-check

      - name: Lint backend
        run: |
          cd backend-hono
          npm run lint

      - name: Test backend
        run: |
          cd backend-hono
          npm run test

  # Deploy frontend to Cloudflare Pages
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: hay-school-react/package-lock.json

      - name: Install dependencies
        run: |
          cd hay-school-react
          npm ci

      - name: Build
        run: |
          cd hay-school-react
          npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: hay-school-frontend
          directory: hay-school-react/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  # Deploy backend to Cloudflare Workers
  deploy-backend:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend-hono/package-lock.json

      - name: Install dependencies
        run: |
          cd backend-hono
          npm ci

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: backend-hono
