name: Deploy to Cloudflare

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Deploy Backend (Cloudflare Workers)
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-hono

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend-hono/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build backend
      run: npm run build

    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        workingDirectory: backend-hono

  # Deploy Frontend (Cloudflare Pages)
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hay-school-react

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build frontend
      run: npm run build

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: hay-school-frontend
        directory: hay-school-react/dist
        # Only deploy on push to main/master, not on PRs
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
